### ISSUE TITLE
增加导出代码

### ISSUE THREAD

**Issue by nchen194** [wukongdaily/OpenBackRestore#1]
能力有限，用了简单的命令，增加导出，抛砖引玉，大神不要喷
    
cp backup.tar.gz /root/backup/ #这是将大佬的文件拷贝出来，可以把“/root/backup”改成你想要的路径
find  /root/backup/ -mtime +3   -exec rm -rf  {} \; #怕备份的文件过多过大，做了个定时清理，可以在+后面改成你想保留的天数，“/root/backup/ ”这里需要和上一行的路径对应

**Comment by wukongdaily** [comment]
嗯 增加了自定义备份的路径。若用户传入备份路径则使用用户定义的路径，若不传入则使用默认备份路径。
https://github.com/wukongdaily/OpenBackRestore/wiki

**Comment by a5412398** [comment]
> 嗯 增加了自定义备份的路径。若用户传入备份路径则使用用户定义的路径，若不传入则使用默认备份路径。 https://github.com/wukongdaily/OpenBackRestore/wiki

谢谢悟空大佬！！！！这个好用！
