### ISSUE TITLE
备份出来的文件大小太小，感觉没备份完全，是第三方固件的问题吗？

### ISSUE THREAD

**Issue by SakiBiAnNya** [wukongdaily/OpenBackRestore#2]
![eb360f3ed99194113246891a0d220a7f](https://github.com/wukongdaily/OpenBackRestore/assets/40420771/edea7562-cf7d-4a57-8eca-f9af6864b5f5)

**Comment by wukongdaily** [comment]
不是哦。我并没有适配ImmortWrt哦。它并不是用overlayFS文件系统的。如果网友呼声比较高 我回头单独适配。
目前支持的OpenWrt系统列表如下
1、软路由iStoreOS(x86_64 | ARM64) ✅
2、兼容机型：MT3000/2500/6000 ✅
3、OpenWrt by Kiddin(openwrt.ai 在线定制的)✅
4、OpenWrt by eSirPG ✅

**Comment by wukongdaily** [comment]
5、ImmortalWrt（squashfs-combined）✅
6、ImmortalWrt（ext4-combined）❌ 适配中...
