### ISSUE TITLE
下载的备份文件可以重命名吗？

### ISSUE THREAD

**Issue by BL1ACH** [wukongdaily/OpenBackRestore#3]
我家里两根网线俩设备俩is，一个主路由一个胖路由，请问下载的备份文件可以重命名吗？是否影响恢复？
如果不可以只能建俩文件夹分别保存备份文件了。。

**Comment by dayunnas** [comment]
胖路由有多胖，有没有200斤？

**Comment by wukongdaily** [comment]
这个项目提供了自定义备份路径的方法：https://github.com/wukongdaily/OpenBackRestore/wiki
你可以将不同的备份文件放在不同的文件夹。但是名称就是：backup.tar.gz  不要变。
至于恢复工作，通过文件传输工具 将需要恢复的备份文件上传。然后执行恢复。

之所以要这样做 ，就是要尽可能的使程序简单。因为如果文件名不同的话，程序还需要判断它到底是否是恢复文件。而是不是恢复文件 其实用户最清楚。程序却很难判断它是不是恢复文件。所以就别改名称啦。备份的时候，放在不同的文件夹即可。

**Comment by BL1ACH** [comment]
明白了，感谢。
